# Generated by Django 5.2.7 on 2025-10-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='redeemed_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
