# Generated by Django 5.2.7 on 2025-10-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sale_redeemed_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='earned_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
