# Generated by Django 5.2.7 on 2025-10-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customer_options_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchased_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
