# Generated by Django 5.2.7 on 2025-12-05 11:55

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_purchase_purchaseitem_supplierpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(default=app.models.generate_shop_id, max_length=6, unique=True)),
                ('shop_name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email_or_link', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/')),
                ('plan', models.CharField(choices=[('trial', 'Free Trial (7 Days)'), ('monthly', 'Monthly 299 BDT'), ('yearly', 'Yearly 2499 BDT')], max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.supplier'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=10)),
                ('sender_last4', models.CharField(max_length=4)),
                ('amount', models.PositiveIntegerField()),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request', to='app.shop')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
        migrations.AddField(
            model_name='expense',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('shop', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('shop', 'invoice_no')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('shop', 'name')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
