# Generated by Django 5.2.7 on 2025-12-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_customerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('due', 'Due')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='plan',
            field=models.CharField(choices=[('trial', 'Free Trial (7 Days)'), ('monthly', 'Monthly 750 BDT'), ('yearly', 'Yearly 6990 BDT')], max_length=10),
        ),
    ]
