# Generated by Django 5.2.7 on 2025-12-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_sale_due_amount_sale_paid_amount_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='trx_id',
        ),
    ]
