# Generated by Django 5.2.7 on 2025-12-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_sale_due_amount_remove_sale_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('due', 'Due')], default='cash', max_length=10),
        ),
    ]
