# Generated by Django 5.2.7 on 2025-12-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_sale_due_amount_sale_paid_amount_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('due', 'Due'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
