# Generated by Django 5.2.7 on 2025-12-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_sale_trx_id_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='plan',
            field=models.CharField(choices=[('trial', 'Free Trial (7 Days)'), ('monthly', 'Monthly 750 BDT'), ('yearly', 'Yearly 7990 BDT')], max_length=10),
        ),
    ]
