# Generated by Django 5.2.7 on 2025-12-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_shop_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier'), ('manager', 'Manager')], default='admin', max_length=20),
        ),
    ]
