# Generated by Django 5.2.7 on 2025-12-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_userprofile_is_owner_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
    ]
