# Generated by Django 5.2.7 on 2026-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_userprofile_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
