# Generated by Django 5.2.7 on 2026-01-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_userprofile_role_alter_userprofile_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_purchases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
