# Generated by Django 5.2.7 on 2026-01-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_userprofile_can_manage_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('seller', 'Seller'), ('cashier', 'Cashier')], default='admin', max_length=20),
        ),
    ]
