# Generated by Django 5.2.7 on 2026-01-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='method',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='sender_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
