# Generated by Django 5.2.7 on 2026-01-03 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_paymentrequest_plan_alter_paymentrequest_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='app.shop'),
        ),
    ]
