# Generated by Django 5.2.7 on 2026-01-04 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_paymentrequest_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='purchase_price',
            new_name='price_per_pack',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('g', 'Gram'), ('ltr', 'Liter'), ('ml', 'Milliliter')], default='pcs', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='cost_per_base_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='pack_size',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='pack_unit',
            field=models.CharField(choices=[('bag', 'Bag'), ('carton', 'Carton'), ('box', 'Box'), ('strip', 'Strip'), ('bottle', 'Bottle'), ('pack', 'Pack'), ('unit', 'Unit')], default='unit', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='qty_packs',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_base_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.product'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='app.product')),
            ],
            options={
                'ordering': ['variant_name'],
                'unique_together': {('product', 'variant_name')},
            },
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.productvariant'),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('return', 'Return')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('batch_no', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('remaining_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productvariant')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.purchaseitem')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.saleitem')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop')),
            ],
            options={
                'ordering': ['expiry_date', 'transaction_date'],
                'indexes': [models.Index(fields=['product', 'batch_no'], name='app_stockle_product_de1967_idx'), models.Index(fields=['product_variant', 'batch_no'], name='app_stockle_product_791763_idx'), models.Index(fields=['expiry_date'], name='app_stockle_expiry__6bfd1e_idx')],
            },
        ),
    ]
