# Generated by Django 5.2.7 on 2026-01-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_purchase_price_purchaseitem_price_per_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
