# Generated by Django 5.2.7 on 2026-01-06 21:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_sale_vat_amount_sale_vat_applicable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('source', models.CharField(choices=[('sale', 'Sale'), ('expense', 'Expense'), ('purchase', 'Purchase'), ('supplier_payment', 'Supplier Payment'), ('customer_payment', 'Customer Due Payment'), ('investment', 'Investment/Capital'), ('bank_deposit', 'Bank Deposit'), ('bank_withdrawal', 'Bank Withdrawal'), ('opening_balance', 'Opening Balance'), ('adjustment', 'Adjustment'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='app.customerpayment')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='app.expense')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='app.purchase')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='app.sale')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='app.shop')),
                ('supplier_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='app.supplierpayment')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'date'], name='app_cashtra_shop_id_5d9997_idx'), models.Index(fields=['shop', 'source'], name='app_cashtra_shop_id_ad4483_idx'), models.Index(fields=['shop', 'transaction_type'], name='app_cashtra_shop_id_8b46ec_idx')],
            },
        ),
    ]
